# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatalert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='label_auto',
            field=models.IntegerField(blank=True, choices=[(-1, b'No Label'), (0, b'Review'), (1, b'LE Interest'), (2, b'Urgent!')], default=-1),
        ),
        migrations.AlterField(
            model_name='message',
            name='label_user',
            field=models.IntegerField(blank=True, choices=[(-1, b'No Label'), (0, b'Review'), (1, b'LE Interest'), (2, b'Urgent!')], default=-1),
        ),
    ]
